moul/assh

- .gitignore
- Makefile
- README.md
- docker/Dockerfile
> Added Docker version (#50)

- README.md
- pkg/config/config_test.go
- pkg/config/host.go
* `AskPassGUI`
* `GSSAPIClientIdentity`
* `GSSAPIKeyExchange`
* `GSSAPIRenewalForcesRekey`
* `GSSAPIServerIdentity`
* `GSSAPITrustDns`
* `KeychainIntegration`
> Support of new SSH configuration fields (

- README.md
- pkg/commands/commands.go
- pkg/config/config.go
- pkg/config/host.go
> Use args[0] as ProxyCommand

- .travis.yml
- README.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/host.go
> Initial Aliases support

- README.md
> Document advanced resolving configuration

- README.md
- pkg/commands/commands.go
- pkg/config/config.go
- pkg/config/host.go
> Add an optional 'ASSHBinaryPath' variable in the 'assh.yml' file (#148)

- README.md
- contrib/dummy-config.yml
- pkg/commands/proxy.go
- pkg/config/config_test.go
- pkg/config/host.go
> Refactor the control-master-mkdir behavior

- README.md
- pkg/commands/proxy.go
> Support `ConnectTimeout`

- README.md
> added Ansible example

- README.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/host.go
> Remove case-sensitivity for `Inherits` and `Gateways`

- README.md
- pkg/commands/commands.go
- pkg/commands/graphviz.go
- pkg/config/graphviz/graphviz.go
- pkg/config/graphviz/graphviz_test.go
Signed-off-by: Manfred Touron <m@42.am>
> Add `assh config graphviz --show-isolated-hosts` flag

- README.md
- pkg/commands/commands.go
- pkg/commands/list.go
- pkg/config/option.go
> Improve readability of `assh config list`

- README.md
- pkg/hooks/driver_notification.go
- pkg/hooks/driver_notification_unsupported.go
- pkg/logger/logger.go
- pkg/logger/process.go
- pkg/logger/process_unsupported.go
> OpenBSD support

- README.md
- pkg/config/helpers.go
- pkg/config/host.go
- pkg/config/host_test.go
> Improve hostname output in `assh config list`

- README.md
- pkg/hooks/driver_notification.go
- pkg/hooks/driver_notification_unsupported.go
- pkg/logger/process.go
- pkg/logger/process_unsupported.go
> Fix NetBSD, FreeBSD and Windows builds

- README.md
> OpenSSH has native support for includes, update docs

- README.md
- pkg/commands/build.go
- pkg/config/config.go
> Fix an error message on first build

- README.md
- pkg/commands/commands.go
- pkg/commands/graphviz.go
- pkg/config/graphviz/graphviz.go
- pkg/config/host.go
> Support wildcards in Graphviz config export

- Makefile
- README.md
- pkg/config/config.go
> Rewrite .ssh/config file atomically

- Makefile
- README.md
- pkg/commands/build.go
- pkg/commands/commands.go
- pkg/commands/proxy.go
- pkg/config/config.go
- pkg/config/host.go
> Add possibility to disable automatic configuration rewrite

- pkg/logger/process.go
This is not feature complete / very useful yet, there are likely still other places where quiet mode would be useful too.
> Add quiet option check

- README.md
- pkg/hooks/driver_exec.go
Fix https://github.com/moul/advanced-ssh-config/issues/254#issuecomment-357210245
> Add more shell propositions for the 'exec' hook

- pkg/commands/proxy.go
Signed-off-by: Noel Georgi <18496730+frezbo@users.noreply.github.com>
> Fixing wrong check

- .gometalinter.json
- .travis.yml
- Makefile
- README.md
- cmd/assh/main.go
- pkg/config/config.go
- pkg/config/graphviz/graphviz.go
- pkg/config/host.go
- pkg/hooks/hooks.go
- pkg/logger/logger.go
- pkg/logger/process.go
> fix: remove invalid warn

- README.md
- examples/test-263/assh.yml
- pkg/commands/proxy.go
Cherry-picked https://github.com/moul/advanced-ssh-config/commit/68f086ef81f84e16698658fdeaa1b7b0e115bfcb (see https://github.com/moul/advanced-ssh-config/issues/263#issuecomment-406265075)
Addresses #279
> Add return to proxyDirect to avoid double-connection

- .gometalinter.json
- README.md
- examples/test-289/assh.yml
- pkg/commands/proxy.go
- pkg/config/config.go
- pkg/config/host.go
> feat: add 'GatewayConnectTimeout' (fix #289)

- README.md
- pkg/commands/info.go
> feat: print version in 'assh info'

- pkg/commands/wrapper.go
> Don't pass invalid options to the SSH binary

- pkg/commands/proxy.go
This is to address #342 
```yaml
myhost:
Gateways:
- direct
- GATEWAY_THAT_WOULD_FAILS
```
```sh
$ ssh myhost
2020/04/28 14:49:33 direct
2020/04/28 14:49:35 GATEWAY_THAT_WOULD_FAILS
channel 0: open failed: administratively prohibited: open failed
stdio forwarding failed
ERROR	Failed to use 'direct' connection with error:	{"error": "failed to dial: dial tcp 123.456.789.00:22: i/o timeout", "errorVerbose": "dial tcp 123.456.789.00:22: i/o timeout\nfailed to dial\nmoul.io/assh/v2/pkg/commands.proxyGo\n\t/home/soraxas/git-repo/assh/pkg/commands/proxy.go:471\nmoul.io/assh/v2/pkg/commands.proxyDirect\n\t/home/soraxas/git-repo/assh/pkg/commands/proxy.go:305\nmoul.io/assh/v2/pkg/commands.proxy\n\t/home/soraxas/git-repo/assh/pkg/commands/proxy.go:240\nmoul.io/assh/v2/pkg/commands.runProxyCommand\n\ …
```
> feat: Cleaner error handling for looping over gateways

- .github/renovate.json
- rules.mk
more details: https://github.com/moul/repoman
> chore: repo maintenance 🤖

- pkg/config/host.go
This PR adds two SSH configuration options which I regularly use in my configuration.
> feat: add 'CertificateFile', and 'CASignatureAlgorithms'

- pkg/commands/proxy.go
Fix #393.
Also, remove the gateway name from `%h` replace in `expandSSHTokens`. Only
add the gateway name in the path here has no effect on raw `ssh`
command, because the raw `ssh` command will only replace the `%h` with
the remote hostname.
> fix: always create empty directory under controlpath

- AUTHORS
- contrib/completion/bash_autocomplete
- contrib/completion/zsh_autocomplete
- go.mod
- go.sum
> fix: bump gopsutil

- .github/workflows/ci.yml
> test(ci): test on go1.18

- .github/workflows/ci.yml
- .golangci.yml
- AUTHORS
- go.mod
- pkg/hooks/driver_notification.go
- pkg/hooks/driver_notification_unsupported.go
- pkg/logger/process.go
- pkg/logger/process_unsupported.go
- pkg/templates/templates.go
> chore: fix golangci
